# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PWAReactNativeWrapper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PWAReactNativeWrapper
  rn_path = '../node_modules/react-native'

  # Third party deps podspec link
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"

  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTSettings',
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTImage',
    'RCTLinkingIOS',
    'RCTVibration',
    # Add any other subspecs you want to use in your project
  ]

  pod 'DoubleConversion',
    :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "#{rn_path}/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  target 'PWAReactNativeWrapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PWAReactNativeWrapper-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PWAReactNativeWrapper-tvOS

  target 'PWAReactNativeWrapper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name == 'Staging'
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Staging'
          config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
      end
    end
    targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    # if target.name == "React"
    #   target.remove_from_project
    # end
  end
end